#!/bin/bash

your_id=${USER}
echo Resetting pipes, memory watcher.
rm -r '/Users/$your_id/Library/Application Support/Dolphin/Pipes'
rm -r '/Users/$your_id/Library/Application Support/Dolphin/MemoryWatcher'
echo Reset. Need to run smashbot.py to reinitialize these files.