#!/bin/bash

echo Resetting pipes, memory watcher.
rm -r '/Users/'$USER'/Library/Application Support/Dolphin/Pipes'
rm -r '/Users/'$USER'/Library/Application Support/Dolphin/MemoryWatcher'
echo Reset. Need to run smashbot.py to reinitialize these files.